### ISSUE TITLE
Is this code meant to be open source? 

### ISSUE THREAD

**Issue by edunham** [ogdch/s3-logs-analyzer#1]
You haven't published a license for the code, so I don't know whether it's okay to use and modify it. 
Please add a license if the repository is meant to help others and allow contributions. 

http://choosealicense.com/ can help you find a license that correctly summarizes what you intended by publishing the code. 

Thanks!

**Comment by metaodi** [comment]
@edunham thanks for this input, it is definitely meant to be open source. We forgot to add a proper LICENSE file, I just fixed that :)

**Comment by edunham** [comment]
Thanks!
